language: node_js
node_js: 10
cache: npm
before_install:
- cd eukanuber-backend
install:
- npm ci
script:
- npm run build
- npm run coverage
deploy:
  provider: heroku
  app: eukanuber-backend
  api_key:
    secure: EPOPNYf5oHQrYFnB40Pk8gBoqMoLtXMRiY+TKTsleOZLBR4d22vQGuRcTv4ARUiBddgWugR7UxKDBAEp1UhU1l/6+wJzLF3Kc/qnaTC2DDrsCwF5ADEI+HsU044GYbpnxtrH33a88GdeOJGezVFk2LXdgix1hF4FIFfAkDNUSIbUoHggBpVdPCofkBDYDsAYv7H1Dk3YAgHsrJCWixWw4ahLcffwu4EPaI6Pv5BmF/LXXhE1kkEO3v4lLF4Lz/hVBS/+PKidjK0SAXAqwR6KjGyEck9qirRgDo+FiGijLUvPWArtcc9fVbRlPmUJinGFO9rKMf/L5m0QaSDeR0o9UrF0HnOI+XXvy58BCy6aM+JRhr2qgMbljXKF0FzCDJ7kTbZKzDS+/yAZK5zKlAkFKJIj1s2Kwj2OkN+RDRy+IeRU23Ib4EfWuN/xuKQw0qwjFDWxd0cBLtefX05EG2Y8Ema5kIaXDo7ejmJ1QlZruCm5mvjC9muXkOyHjmyu8S2rE8Z81rO405NyvBvIUowILIolO5ht7z8MEZNSS5DNKYEiAcBYxT4Jq5wd11b+WWrkj10w4Rtrutc9dK9uM1zMJAaYqsztKfaA/UHq3JgpaOwNC42TBtWvbgapFXpKM+5gvOY07Ro6u3E7dsdD5zoIHeomy3ZatgMUh4x01/k/xRE=
