language: node_js
node_js: 10
cache: npm

before_install:
  - cd eukanuber-backend

install:
  - npm ci

script:
  - npm run build
  - npm run coverage

deploy:
  provider: heroku
  app: eukanuber-backend
  api_key:
    secure: CLSYNUvCXkg+y/6/5uBMMaw1qEDn4gedxVSiTQ+g2cEh9V3/MELjPE4+ATJ0IKWKKw5Ct0py/gT2ZKOvloi8SBS0216zNa4VsTVxJZnAQchjnvrJxtle6yggT+0hqqpYGgGFHvDfr2IhgJsNCL9AvnkLchPvFQI5Nf2IrlaWqTqWp8sjOCHhiZVBvHjM8iWJDqnMGev0EcEfcuROGJqYT+Jm/k/HHPaqBwvDN63USqYRnUdefqqjmtAo9AqtLjgAqcwhRP7a0s9l+G2jAyfSCXZXRcZA3wgwgbiS5l7zfWhlVG1GxTVpn6ThQo5b0qEh0wxEo+gY8eMco94jD0gfNI9huIcWoQoGb5z62rMrCB917mg3Blt+DpNIvbE2CuY/U+Q/e88Dt8AvZ2NLP8JA45/QzG4hd8qCkHMLTH1ktQSQynwbpTGfCZDUDJLPH87vabg7G9HzBnYTsoL+BEu/spGGHykwmJ/2QDsVdjoUfdyUBJIZeF79HELJ2UltNQrH6Yd3FVWog02MbXtr4KibLehTLUMINxMWYqzw2H3KjVoG4mmkfQTQlciCAQ5niorg4QNYe2BhUo4Ut3Fhf9T1FSPR+kLZJP1rkb14xOMm157ADfxm2DBj9l3HHqfZnPQZOU3rkZqsTuMRKvH6mmzaraVO0lAbdRY/6Y+5FV+6b2A=
